name: nutrigen_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.5.2
  http: ^0.13.6
  cupertino_icons: ^1.0.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  intl_phone_field: ^3.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/nutrigen_logo.png
    - assets/healthy-diet.png
    - assets/scan.png
