// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUFP8ufkYIuOg0zk2Hzo4749jUFV46pkg',
    appId: '1:334660570249:web:1822736dd820f6a1cf0a58',
    messagingSenderId: '334660570249',
    projectId: 'nutrigen-ui',
    authDomain: 'nutrigen-ui.firebaseapp.com',
    storageBucket: 'nutrigen-ui.firebasestorage.app',
    measurementId: 'G-XS0T8E23GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANOGtHLvkb-SRAGcn9bg3xFAmXARzemRg',
    appId: '1:334660570249:android:a6c2bacd6a90dfa1cf0a58',
    messagingSenderId: '334660570249',
    projectId: 'nutrigen-ui',
    storageBucket: 'nutrigen-ui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2EUtwmVqaUpYAIpgmd8QDymqjgP65bEY',
    appId: '1:334660570249:ios:928c91f891546eb4cf0a58',
    messagingSenderId: '334660570249',
    projectId: 'nutrigen-ui',
    storageBucket: 'nutrigen-ui.firebasestorage.app',
    iosBundleId: 'com.example.nutrigenUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2EUtwmVqaUpYAIpgmd8QDymqjgP65bEY',
    appId: '1:334660570249:ios:928c91f891546eb4cf0a58',
    messagingSenderId: '334660570249',
    projectId: 'nutrigen-ui',
    storageBucket: 'nutrigen-ui.firebasestorage.app',
    iosBundleId: 'com.example.nutrigenUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUFP8ufkYIuOg0zk2Hzo4749jUFV46pkg',
    appId: '1:334660570249:web:7c43852a259ae68ccf0a58',
    messagingSenderId: '334660570249',
    projectId: 'nutrigen-ui',
    authDomain: 'nutrigen-ui.firebaseapp.com',
    storageBucket: 'nutrigen-ui.firebasestorage.app',
    measurementId: 'G-ML9N7L1JV0',
  );

}